### ISSUE TITLE
WSJ Paywalled again

### ISSUE THREAD

**Issue by rourpab** [jdai8/wsj#1]
Cool extension until recently, hasn't been working on WSJ lately..

**Comment by jdai8** [comment]
Yeah.. it seems like setting the `referer` header doesn't work anymore (tested with Facebook and Twitter). I don't know a solution other than hoping the WSJ goes back to the old behavior.

Gonna close this for now - happy to reopen if someone finds a fix.

I'm glad you enjoyed it while it lasted :)
