### ISSUE TITLE
No longer in the Chrome Webstore!

### ISSUE THREAD

**Issue by mc510** [jdai8/wsj#2]
https://chrome.google.com/webstore/detail/free-wsj/kjigmmnfcbcipeibeogofhacnknndbbk yields 404 error.

Possible to sideload?

**Comment by jdai8** [comment]
Yeah it got taken down by Google. You can install it yourself by following the steps at https://developer.chrome.com/extensions/getstarted.

But it probably won't work anyways... See #1
